apiVersion: apps/v1
kind: Deployment
metadata:
  name: modusbox-stock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modusbox-stock-api
  template:
    metadata:
      labels:
        app: modusbox-stock-api
    spec:
      containers:
        - name: modusbox-stock-api
          image: "modusbox-stock-api:v1"
          env:
            - name: PORT
              value: "8080"
            - name: FINHUBTOKEN
              value: "braf1cnrh5rbgnjpsv2g"
            - name: ISSUER
              value: "https://dev-283920.okta.com/oauth2/default"
            - name: SCOPE
              value: "stock_api"
            - name: CLIENT_ID
              value: "0oacgteb501eaj6KX4x6"
            - name: VERSION
              value: "v1"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 20
          ports:
            - containerPort: 8080
          imagePullPolicy: Never