apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: modusbox-stock-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: modusbox-stock-api
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80