apiVersion: v1
kind: Service
metadata:
  name: modusbox-stock-api
spec:
  type: NodePort
  selector:
    app: modusbox-stock-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
      protocol: TCP